#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [ -z "$1" ]; then
  echo "Usage: $0 <filename.md> [output_type] [heading_shift]"
  echo "  filename.md: input markdown file"
  echo "  output_type: pdf (default) or beamer"
  echo "  heading_shift: integer for heading level shift (for beamer only, default is -1)"
  exit 1
fi

input_path="$1"
to_type=${2:-pdf}
heading_shift=${3:--1}

input_dir=$(dirname "$input_path")
input_file=$(basename "$input_path")
output_file="${input_file%.*}.pdf"

if [ -n "$input_dir" ] && [ "$input_dir" != "." ]; then
  cd "$input_dir" || exit 1
fi

if [ $to_type = "pdf" ]; then
    if pandoc -f gfm+raw_attribute --pdf-engine=xelatex \
       -V CJKmainfont='Noto Serif CJK SC' \
       -V geometry:margin=1in \
       -V linestretch:1.2 \
       --metadata date=""  $extra_opt \
       "$input_file" -o "$output_file" ; then
        echo "Generated '$(pwd)/$output_file'"
    fi
fi

if [ $to_type = "beamer" ]; then
    # pandoc markdown support columns for slides
    if pandoc -f markdown+lists_without_preceding_blankline --pdf-engine=xelatex -t beamer \
       --shift-heading-level-by=$heading_shift \
       -V CJKmainfont='Noto Serif CJK SC' \
       --metadata date=""  $extra_opt \
       "$input_file" -o "$output_file" ; then
        echo "Generated '$(pwd)/$output_file'"
    fi
fi

if [ -n "$input_dir" ] && [ "$input_dir" != "." ]; then
  cd - > /dev/null 2>&1
fi
